#Open Peer Review

This exercise is about identifying reproducibility issues in a scientific publication. We use the criteria for reproduciblity that are publically available via here

Transparency Criteria	Definition	Response Type
Study Purpose	A concise statement in the introduction of the article, often in the last paragraph, that establishes the reason the research was conducted. Also called the study objective.	Binary
Data Availability Statement	A statement, in an individual section offset from the main body of text, that explains how or if one can access a study’s data. The title of the section may vary, but it must explicitly mention data; it is therefore distinct from a supplementary materials section.	Binary
Data Location	Where the article’s data can be accessed, either raw or processed.	Found Value
Study Location	Author has stated in the methods section where the study took place or the data’s country/region of origin.	Binary; Found Value
Author Review	The professionalism of the contact information that the author has provided in the manuscript.	Found Value
Ethics Statement	A statement within the manuscript indicating any ethical concerns, including the presence of sensitive data.	Binary
Funding Statement	A statement within the manuscript indicating whether or not the authors received funding for their research.	Binary
Code Availability	Authors have shared access to the most updated code that they used in their study, including code used for analysis.	Binary
Table clarification The Transparency Criteria are criteria you need to score the article of your choice for. Read them carefully and discuss with another course participant if you do not understand them. Each Tranparance criterion comes with a Definition that explains the criterion in more details. These descriptions are particularly helpful to understand what the criterium entails and what to look for in the article. The Response Type is the actual score

In this assisgment you need to find a scientific article yourself, using PubMed or another database or repository. Use only Open Access articles. Having an article in hand, go over the table above and score the article according the criteria. Be sure to select a primary article that presents a study using data from experimental work . This can be laboratory experiments or in silico experiments. Reviews and meta analysis are not suitable for this assignment

To guide your search you can choose between these topics

“Coronavirus / COVID-19”
“The effects of compound on an organism / Toxicology”
“The effectiveness of a drug or treatment in an animal study”
“The effects of a compound investigated in a cell or organoid system”

https://www.biorxiv.org/content/10.1101/2020.10.02.322917v2.full

Study Purpose : er wordt in de samenvatting kort uitgelegd wat voor belanger er is om dit onderzoek uit te voeren
Data Availability Statement: niet aanwezig
Data Location: er wordt wel bescreven hoe de data er uit moet zien en er zijn verwijzingen naar waar artikelen waar in wordt beschrevenhoe de data verzameld is. Er staat niet waar je de gebruikte data terug kan vinden.
Study Location: in de materiaal en methode sectie staat geen informatie over waar het onderzoek is uitgevoerd
Author Review: de gegevens van de auteurs zijn niet makkelij te verkrijgen, de namen van de auteurs staan boven aan het artkel maar verdere contact gegevens staan niet op de pagina zelf.
Ethics Statement: in de introductie staat kort iets over de ethiek
Funding Statement: er wordt niets gezegt over de financiering
Code Availability: er wordt geen code gedeeld in het artikel

TIPS
If you do not know where to start your literature search start here: https://www.biorxiv.org/
This assignment is not about the topic you select, so try to do that quickly
You may want to cheat and select an article that scores TRUE on the Data Availability Statement, because that enables you to use the this article again in one of the next assignments.
PART 1 To complete part 1, execute activity A to G

Initiate an empty RMarkdown file in your RStudio environment and provide author and title (after the title of this exercise)
Search for a primary Open Access article on one of the above listed topics, using Pubmed Central
Read the article diagonally to check if is indeed a primary article describing emperical scientific findings.
Include the reference to this article in your Rmd file
Score the article on the basis of the above ‘Repita’ criteria
Write an Rmarkdown report on your findings, including the table above and some information about the article such as general aim, short methods and results. If data is available, try including some
Store the source Rmd and knitted HTML in a folder called ‘Rmd’ in your course RStudio project. You will need it again later in the course
PART 2 To complete this assignment you will have to execute activity H to P

Using the OSF website, select a project that addresses an aspect of the SARS-Cov-2 virus.
Select a project that has a dataset and R-code shared in the project environment.
Have a look at the code. Describe in your own words what the code intents to achieve.
In terms of readibility of the code, how would you grade (1(very bad)-5(very good)) the code available.
Download the code and the data to a new RStudio project
Run the script or code that is available to reproduce at least 1 figure
When you encounter errors or flaws in the script, try fixing them and record your changes.
Taken together on a scale from 1 (very hard) to 5 (very easy), how much effort did it take you to reproduce the visualization from the project, report or article
Generate an RMarkdown script that contains the details on the project you selected, the code you used to create the visualization and your score for reproducibility.
resource: https://www.researchgate.net/publication/340244621_Reproducibility_and_reporting_practices_in_COVID-19_preprint_manuscripts/fulltext/5e81f9fd92851caef4ae37ba/Reproducibility-and-reporting-practices-in-COVID-19-preprint-manuscripts.pdf
```{r}
#https://osf.io/gkcn7/
library(readxl)
#salmonellacfu <- read_excel("salmonella")
```